# Generated by Django 2.2 on 2022-10-02 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('email', models.CharField(max_length=20, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('date_cancel', models.DateTimeField(default=datetime.datetime(2022, 11, 1, 21, 31, 15, 981523, tzinfo=utc), verbose_name='Дата окончания публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements_app.Author', verbose_name='Автор публикации')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements_app.Category', verbose_name='Категория')),
            ],
        ),
    ]
