# Generated by Django 2.2 on 2022-10-02 22:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0002_auto_20221003_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='count_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date_cancel',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 22, 31, 13, 273594, tzinfo=utc), verbose_name='Дата окончания публикации'),
        ),
    ]
