[tool.poetry]
name = "m-19-prod"
version = "0.1.0"
description = ""
authors = ["liverpool <fleetvord@gmail.com>"]


[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
